### ISSUE TITLE
An issue with code that fails to end the discover phase

### ISSUE THREAD

**Issue by luckNuma26** [fuzztruction/fuzztruction#1]
I find that when FT is running, it is always in the **FuzzingPhase::Discovery**, and I find that the exit stage from dicover is **entries.is_empty()**. But I noticed that **e.generation() == 0** was always in the queue,

The command to run is
`sudo ./target/debug/fuzztruction ./fuzztruction-experiments/comparison-with-state-of-the-art/configurations/pngtopng_pngtopng/pngtopng-pngtopng.yml fuzz -j 1 -t 10m`

Code exists in
`fuzztruction/scheduler/src/fuzzer/worker_impl/scheduling.rs`

```rust
let queue = self.queue.lock().unwrap();
  // The worker is in discovery phase.
let mut entries = queue.filter(|e| { e.generation() == 0
    && !e.stats_ro().blacklisted()
    && !e.stats_ro().is_phase_done(FuzzingPhase::Discovery)
});
if entries.is_empty() {
	...
}else {

  entries.shuffle(rng);

  let entries_before_pop__length = entries.len();
  println!("before entries.pop() entries length: {}", entries_before_pop__length);
  let queue_before_pop__length = queue.len();
  println!("before entries.pop() queue length: {}", queue_before_pop__length); 
                                              
   entries.pop().unwrap();

   let entries_after_pop__length = entries.len();
   println!("after entries.pop() entries length: {}", entries_after_pop__length);
   let queue_after_pop__length = queue.len();
   println!("after entries.pop() queue length: {}", queue_after_pop__length);  
}
```

The result of running is

```sh
before entries.pop() entries length: 1
before entries.pop() queue length: 1
after entries.pop() entries length: 0
after entries.pop() queue length: 1
```
This means that **entry with e.generation() == 0 always in the queue**, which creates an infinite loop, unable to reach the next stage.

entries = queue -> entries.pop() -> entries = queue

**Comment by nbars** [comment]
Hello,

Please attach a log file with the log level set to debug (configurable via a command line flag). Providing just one core and a timeout of 10 minutes I likely insufficient for all instrumentation sites to be processed by the discovery phase in time. Please note that we used 64 cores during our evaluation. 

I am not quite sure in regard to the problem you are describing. Entries from the first generation (i.e., `generation() == 0`) are only returned if the discovery phase was not finished for them yet:
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/scheduling.rs#L160-L164

Thus, after the discovery phase for all initial inputs was executed, the next phase is chosen
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/scheduling.rs#L165-L176

**Comment by luckNuma26** [comment]
Thanks for your reply, but I still haven't found the conditions for the end of discover. I find condition 
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/scheduling.rs#L165-L176

https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/phases/discovery.rs#L24-L47

is there any other end condition I can't find

**Comment by nbars** [comment]
The statement 
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/scheduling.rs#L160-L164
will yield an empty `entries` vector if `e.stats_ro().is_phase_done(FuzzingPhase::Discovery) ` is true for all entries in the queue (which is set if the discovery phase was executed for a specific entry).

This empty `entries` vector will trigger this code
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/scheduling.rs#L165-L176
and causes the phase to be switched.

The code related to the discovery phase is never called if it was marked as done by the snippet above:
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/main_loop.rs#L129-L135

**Comment by luckNuma26** [comment]
This is very wired Because I haven't found a way to empty entries  although `entries.pop().unwrap()` may be empty, but `entries.is_empty()` is **before** `entries.pop().unwrap()`, but as I said earlier, **new entries come from queue**, but `entries.pop()` **does not reduce** the number of elements in `queue`. And I can't find any other way to reduce the number of elements in queue.

https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/scheduling.rs#L155-L186

**Comment by nbars** [comment]
In fuzzing terminology, the set of *interesting* inputs (i.e., those that yield new coverage) are typically kept in a structure called a queue. From this queue, elements are chosen, but not removed, for further fuzzing efforts. There is no need for the number of elements in the queue to be reduced in order for the code to work correctly.

> I haven't found a way to empty entries...

The discovery phase is done as soon as `entries` is empty: This is the case if the filter expression yields no elements because all of the initial queue entries (`generation() == 0`) have been processed by the discovery phase (`e.stats_ro().is_phase_done(FuzzingPhase::Discovery)`) or are blacklisted (`e.stats_ro().blacklisted()`) because, e.g., the generator failed to process the associated input.

**Comment by luckNuma26** [comment]
Thank you very much. I seem to understand. The final end of the discover phase is
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/phases/discovery.rs#L68-L72

However, the patch point I obtained by experimenting with openssl is`Found 220444 patch points in total` (Although I know you limited it to 20,000). Maybe the previous discover phase took too long. Made me think I couldn't quit, I was wondering how long have you been through the openssl discover phase?

Another question is why FT didn't choose  **ASAN( AddressSanitizer)** when compiling  `fuzztruction/fuzztruction-experiments/comparison-with-state-of-the-art/binaries/XXX/ft`? I think this can help FT find more mistakes.

**Comment by nbars** [comment]
> Thank you very much. I seem to understand. The final end of the discover phase is
> 
> https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/scheduler/src/fuzzer/worker_impl/phases/discovery.rs#L68-L72

Exactly :)


> However, the patch point I obtained by experimenting with openssl is`Found 220444 patch points in total` (Although I know you limited it to 20,000). Maybe the previous discover phase took too long. Made me think I couldn't quit, I was wondering how long have you been through the openssl discover phase?

I have no recording of how long it takes. However, since all the RSA stuff is comparably slow, this will take a considerable amount of time. You could artificially lower the limit of used patch points in order to speed up the process. 

> Another question is why FT didn't choose **ASAN( AddressSanitizer)** when compiling `fuzztruction/fuzztruction-experiments/comparison-with-state-of-the-art/binaries/XXX/ft`? I think this can help FT find more mistakes.

We opted not to use ASAN to avoid further performance penalties since we already got a ~2x slowdown because we need to execute two instead of one application (as commonly done for fuzzing). While ASAN may be advantageous, we tried to compensate by processing all queue entries via `valgrind` (see the `valgrind` subcommand).
