### ISSUE TITLE
A question about the mutation of FT

### ISSUE THREAD

**Issue by luckNuma26** [fuzztruction/fuzztruction#2]
I assumed that **changing the icmp value** would **give x a different value** to achieve a **mutation**, but I ran it for a long time and the **output was the same**

source.c

````c
int main(int argc, char *argv[]) {
    if (argc != 2) {
        printf("Usage: %s <outputfile>\n", argv[0]);
        return 1;
    }

    char *outputFileName = argv[1];
    FILE *file = fopen(outputFileName, "w");

    int x = 0;
    int result = 1;
    if(result == 1){  
        x = 1;
    }

    if(result == 2){//If the icmp directive is changed, the value of X becomes 2,
        x = 2;
    }

    if(result == 3){
        x = 3;
    }
    if (file != NULL) {
        fprintf(file, "Result: %d", x);
        fclose(file);
    } else {
        printf("Failed to open file for writing.\n");
    }

    return 0;
}



````

source.ll
export FT_HOOK_INS=icmp

````ll
....
if.end9:                                          ; preds = %if.then8, %if.end
  %10 = load i32, i32* %result, align 4
  %cmp10 = icmp eq i32 %10, 2
  call void (i64, i32, i8*, i32, ...) @llvm.experimental.patchpoint.void(i64 53, i32 32, i8* null, i32 0, i1 %cmp10)
  br i1 %cmp10, label %if.then12, label %if.end13

if.then12:                                        ; preds = %if.end9
  store i32 2, i32* %b, align 4
  br label %if.end13

if.end13:                                         ; preds = %if.then12, %if.end9
  %11 = load i32, i32* %result, align 4
  %cmp14 = icmp eq i32 %11, 3
  call void (i64, i32, i8*, i32, ...) @llvm.experimental.patchpoint.void(i64 53, i32 32, i8* null, i32 0, i1 %cmp14)
  br i1 %cmp14, label %if.then16, label %if.end17
````

source.asm

````asm
40129f:	83 7d d8 01          	cmp    DWORD PTR [rbp-0x28],0x1
  4012a3:	41 0f 94 c0          	sete   r8b
  4012a7:	44 88 45 a7          	mov    BYTE PTR [rbp-0x59],r8b
  4012ab:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012b2:	02 00 00 
  4012b5:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012bc:	02 00 00 
  4012bf:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012c6:	02 00 00 
  4012c9:	66 90                	xchg   ax,ax
  4012cb:	44 8a 45 a7          	mov    r8b,BYTE PTR [rbp-0x59]
  4012cf:	41 f6 c0 01          	test   r8b,0x1
  4012d3:	0f 85 05 00 00 00    	jne    4012de <main+0x13e>
  4012d9:	e9 07 00 00 00       	jmp    4012e5 <main+0x145>
  4012de:	c7 45 dc 01 00 00 00 	mov    DWORD PTR [rbp-0x24],0x1
  4012e5:	31 c0                	xor    eax,eax
  4012e7:	89 c1                	mov    ecx,eax
  4012e9:	83 7d d8 02          	cmp    DWORD PTR [rbp-0x28],0x2
  4012ed:	0f 94 c2             	sete   dl
  4012f0:	48 89 4d 98          	mov    QWORD PTR [rbp-0x68],rcx
  4012f4:	88 55 97             	mov    BYTE PTR [rbp-0x69],dl
  4012f7:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012fe:	02 00 00 
  401301:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  401308:	02 00 00 
  40130b:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  401312:	02 00 00 
  401315:	66 90                	xchg   ax,ax
  401317:	8a 55 97             	mov    dl,BYTE PTR [rbp-0x69]
  40131a:	f6 c2 01             	test   dl,0x1
  40131d:	0f 85 05 00 00 00    	jne    401328 <main+0x188>
  401323:	e9 07 00 00 00       	jmp    40132f <main+0x18f>
  401328:	c7 45 dc 02 00 00 00 	mov    DWORD PTR [rbp-0x24],0x2
  40132f:	31 c0                	xor    eax,eax
  401331:	89 c1                	mov    ecx,eax
  401333:	83 7d d8 03          	cmp    DWORD PTR [rbp-0x28],0x3 
````

patch  point  Mutation Stub

````
Mutation Stub: FunctionInstance {
    asm: [
        "push 0",
        "push rax",
        "push rbx",
        "push rcx",
        "push rdx",
        "mov rax, 0x7ffff36716f0",
        "mov ebx, [rax + 0x1c]",
        "mov dl, [rax + rbx + 0x28]",
        "mov [rsp+0x20], dl",
        "add ebx, 0x1",
        "mov ecx, [rax + 0x20]",
        "cmp ebx, ecx",
        "cmova ebx, ecx",
        "mov dword [rax + 0x1c], ebx",
        "pop rdx",
        "pop rcx",
        "pop rbx",
        "pop rax",
        "xor r8b, [rsp]",
        "add rsp, 0x8",
        "ret",
    ], 
````

The paper says
```
mov ebx, mutation_base
mov eax, [ebx];  offset into msk
mov eax, [ebx+eax+8];  load mask
xor edx, eax ;  apply mask
add [ebx], 4
ret
```
`xor edx, eax;` Will **change the value** of the load instruction,
But no matter how I changed the msk value, **The output has not changed.**  Doesn't this mutation change the icmp value?
For the mutation ,paper said a little brief, I really can not understand
**Can you explain what the mutation of FT is? 
Can you write me an example(code demo) of icmp mutation?**

**Comment by nbars** [comment]
Hey,

The current support for instructions depending on the `*FLAGS` registers is broken. 

This is because LLVM assumes that the `*FLAGS` register gets clobbered by the patch point: 
```
  %10 = load i32, i32* %result, align 4
  %cmp10 = icmp eq i32 %10, 2 // Will be stored in FLAGS 
  call void (i64, i32, i8*, i32, ...) @llvm.experimental.patchpoint.void(i64 53, i32 32, i8* null, i32 0, i1 %cmp10) // clobbering FLAGS
  br i1 %cmp10, label %if.then12, label %if.end13 // Using the value of FLAGS
```

Since LLVM assumes that the register gets clobbered, it recomputes the condition (`4012cf`) after inserting the patch point. Thus, the mutations applied to the condition value passed as an argument to the patch point have no effect.
```
  4012a7:	44 88 45 a7          	mov    BYTE PTR [rbp-0x59],r8b
  4012ab:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012b2:	02 00 00 
  4012b5:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012bc:	02 00 00 
  4012bf:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012c6:	02 00 00 
  4012c9:	66 90                	xchg   ax,ax
  4012cb:	44 8a 45 a7          	mov    r8b,BYTE PTR [rbp-0x59]
  4012cf:	41 f6 c0 01          	test   r8b,0x1
  4012d3:	0f 85 05 00 00 00    	jne    4012de <main+0x13e>
  ```

I recommend sticking to `load` and `store` mutations and disabling the others.

**Comment by luckNuma26** [comment]
Since the **mutation of FT is effective**, it must be possible to **explicitly control** the value of `r8b` to mutate. 
```
mov    r8b,BYTE PTR [rbp-0x59]  //Does mutation of FT change the contents of BYTE PTR [rbp-0x59]? How did he change?
test   r8b,0x1
```
**Or is the FT mutation a black box that cannot be controlled?**

The same goes for the `store` directive
source.ll

  export FT_HOOK_INS=store

````.ll
if.then8:                                         ; preds = %if.end
  call void (i64, i32, i8*, i32, ...) @llvm.experimental.patchpoint.void(i64 33, i32 32, i8* null, i32 0, i32 1)
  store i32 1, i32* %a, align 4
  br label %if.end9
````

source.s

````asm
 4013f1:       83 7d d8 02             cmp    DWORD PTR [rbp-0x28],0x2
  4013f5:       0f 85 32 00 00 00       jne    40142d <main+0x23d>
  4013fb:       31 c0                   xor    eax,eax
  4013fd:       89 c1                   mov    ecx,eax
  4013ff:       48 89 8d 60 ff ff ff    mov    QWORD PTR [rbp-0xa0],rcx
  401406:       2e 66 0f 1f 84 00 00    nop    WORD PTR cs:[rax+rax*1+0x200]
  40140d:       02 00 00 
  401410:       2e 66 0f 1f 84 00 00    nop    WORD PTR cs:[rax+rax*1+0x200]
  401417:       02 00 00 
  40141a:       2e 66 0f 1f 84 00 00    nop    WORD PTR cs:[rax+rax*1+0x200]
  401421:       02 00 00 
  401424:       66 90                   xchg   ax,ax
  401426:       c7 45 c4 02 00 00 00    mov    DWORD PTR [rbp-0x3c],0x2 //Did something change here, did it mutate the value of the store instruction?
  40142d:       83 7d d8 03             cmp    DWORD PTR [rbp-0x28],0x3
````
I want to know how to explicitly control a variable value and operate different outputs, 
Can you give me a code demo?

**Comment by nbars** [comment]
What goal are you pursuing? What kind of code demo do you have in your mind?

We are using [patch  points](https://llvm.org/docs/StackMaps.html) to record live values (e.g., the value passed as source operand to store instructions). Based on such a record (read from the stack map), we know where the value is located during runtime when the corroding patch point is executed. To mutate the recorded live value itself, we are using a JIT engine (`jit.rs`) to generate a code stub that applies the desired mutation. For this prototype, the mutation capabilities are limited to applying a byte mask via bitwise XOR to the to-be-mutated value.

Ultimately, what live value a patch point recorded for the actual binary must be determined by looking into the stack map and inspecting the corresponding patch point manually. Possibly, some optimizations may break the anticipated data flow of the live value, rendering our mutation efforts futile.

**Comment by luckNuma26** [comment]
I'm sorry. I didn't mean to offend
Do **live values** refer to `i32 1` or `i1 %cmp10`?

````
 call void (i64, i32, i8*, i32, ...) @llvm.experimental.patchpoint.void(i64 33, i32 32, i8* null, i32 0, i32 1)
  store i32 1, i32* %a, align 4
 
`"xor dl, [rsp]", //asm.push(format!("xor {}, [rsp]", target_reg));`

````

I want to know, if the value of dl is 0x00, and I change it to 0xFF by flipping it, which affects the branch jump, 

`But then you say. Thus, the mutations applied to the condition value passed as an argument to the patch point have no effect.`

I felt very confused

````
  401317:	8a 55 97             	mov    dl,BYTE PTR [rbp-0x69]
  40131a:	f6 c2 01             	test   dl,0x1
  40131d:	0f 85 05 00 00 00    	jne    401328 <main+0x188>
````

I just don't understand how xor is going to make an impact
Does the XOR operation change the value of `i32 1`? So the store directive puts a different value into it?
Does the XOR operation change the value of `BYTE PTR [rbp-0x69]`?



````asm
  4012e9:	83 7d d8 02          	cmp    DWORD PTR [rbp-0x28],0x2
  4012ed:	0f 94 c2             	sete   dl
  4012f0:	48 89 4d 98          	mov    QWORD PTR [rbp-0x68],rcx
  4012f4:	88 55 97             	mov    BYTE PTR [rbp-0x69],dl
  4012f7:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  4012fe:	02 00 00 
  401301:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  401308:	02 00 00   
  40130b:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
  401312:	02 00 00  ;In this nop instruction here, after the patchpoint XOR operation, what things are changed and what things are mutated?  Is BYTE PTR [rbp-0x69] changed?
  401315:	66 90                	xchg   ax,ax
  401317:	8a 55 97             	mov    dl,BYTE PTR [rbp-0x69]
  40131a:	f6 c2 01             	test   dl,0x1
````

**Comment by nbars** [comment]
> I'm sorry. I didn't mean to offend Do **live values** refer to `i32 1` or `i1 %cmp10`?
> 
> ```
>  call void (i64, i32, i8*, i32, ...) @llvm.experimental.patchpoint.void(i64 33, i32 32, i8* null, i32 0, i32 1)
>   store i32 1, i32* %a, align 4
>  
> `"xor dl, [rsp]", //asm.push(format!("xor {}, [rsp]", target_reg));`
> ```
No offense taken. Live values are those variables alive before and after the patch point. This means all variables (prefixed with `%` in LLVM IR) can be recorded by a patch point. You can see here 
https://github.com/fuzztruction/fuzztruction/blob/35f6482369819c1d9c3c66bd7e00a2482bd72966/generator/pass/fuzztruction-source-llvm-pass.cc#L471-L475
which values are recorded for the respective instructions. For example, for `store` instructions, the location of the to-be-stored value is recorded (the argument at index 0).


> I want to know, if the value of dl is 0x00, and I change it to 0xFF by flipping it, which affects the branch jump,
Sorry, but I do not understand what you are trying to say.


> But then you say: Thus, the mutations applied to the condition value passed as an argument to the patch point have no effect.`
There, we were talking about `icmp` instructions, which are not mutated correctly in the current version of the fuzzer (as explained above).


> I felt very confused
> 
> ```
>   401317:	8a 55 97             	mov    dl,BYTE PTR [rbp-0x69]
>   40131a:	f6 c2 01             	test   dl,0x1
>   40131d:	0f 85 05 00 00 00    	jne    401328 <main+0x188>
> ```
> 
> I just don't understand how xor is going to make an impact Does the XOR operation change the value of `i32 1`? So the store directive puts a different value into it? Does the XOR operation change the value of `BYTE PTR [rbp-0x69]`?
> 
> ```assembly
>   4012e9:	83 7d d8 02          	cmp    DWORD PTR [rbp-0x28],0x2
>   4012ed:	0f 94 c2             	sete   dl
>   4012f0:	48 89 4d 98          	mov    QWORD PTR [rbp-0x68],rcx
>   4012f4:	88 55 97             	mov    BYTE PTR [rbp-0x69],dl
>   4012f7:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
>   4012fe:	02 00 00 
>   401301:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
>   401308:	02 00 00   
>   40130b:	2e 66 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x200]
>   401312:	02 00 00  ;In this nop instruction here, after the patchpoint XOR operation, what things are changed and what things are mutated?  Is BYTE PTR [rbp-0x69] changed?
>   401315:	66 90                	xchg   ax,ax
>   401317:	8a 55 97             	mov    dl,BYTE PTR [rbp-0x69]
>   40131a:	f6 c2 01             	test   dl,0x1
> ```
Without looking into the stack map, there is no way of knowing what value is mutated in which way here. Please keep in mind that the patch point feature itself is not stable, and some patch points may record live values that are not used in the way anticipated during LLVM IR processing by the LLVM pass.

**Comment by luckNuma26** [comment]
Is it through the mutation operation that FT cannot determine **what** is mutated (is the` live value` mutated?)? ? 
What is the **effect** of the mutation? Is it uncertain? 
But it's possible to **produce** a different output, right?

So there's **no way** I can make a **deterministic modification** to `pathc point` that produces a **deterministic result**?

`store i32 1, i32* %a, align 4`
That is, I want to change the **Live values  ` i32 1`** captured by the patch point to `i32 2` through **deterministic modification**, so that the **stored value becomes 2**. There is no way to do this, right?

**Comment by nbars** [comment]
Sorry, but I do not understand your questions. I recommend you read the documentation of LLVM patch points and the LLVM IR.
