### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by tminning** [fuzztruction/fuzztruction#3]
I had a question about which software components (versions) required to build fuzztruction. I was able to run the container just fine but when I try to build fuzztruction on my machine I keep running into problems such as:
![image](https://github.com/fuzztruction/fuzztruction/assets/49421166/f87d7768-be8a-4f69-bbd7-474b8ad62ce0)

Let me know if there is any information I can provide to help you answer my question, thank you!

**Comment by nbars** [comment]
What steps did you perform in particular?

**Comment by tminning** [comment]
Thank you for taking the time to respond, in the end it was a silly mistake on my end due to misreading the documentation.
