### ISSUE TITLE
An error was encountered while configuring the environment

### ISSUE THREAD

**Issue by joengsanyc** [fuzztruction/fuzztruction#4]
Hello, I have some problems in the configuration process and need your help. When I'm about to pull a prebuild to get an image, I have the following issues:
![微信图片_20240221202918](https://github.com/fuzztruction/fuzztruction/assets/160738740/a7449c52-9396-44d4-ae89-9babc483c6d2)
Let me know if there is any information I can provide to help you answer my question, thank you!

**Comment by nbars** [comment]
Hey, the displayed error message states that there is no space left on the device, which is certainly the issue here.

**Comment by joengsanyc** [comment]
But I allocated more than 100GB of hard disk space for the virtual machine

**Comment by joengsanyc** [comment]
Yes, you're right. But I don't know how to deal with this one, I'm just an undergraduate, so I need your help.

**Comment by joengsanyc** [comment]
I have allocated at least 100G of hard disk space for the Ubuntu virtual machine.
My undergraduate supervisor gave me a graduation project on the research of fuzzy testing technology based on data injection, and the reference paper he gave me was your paper titled
Fuzztruction: Using Fault Injection-based Fuzzing to Leverage Implicit Domain Knowledge

**Comment by nbars** [comment]
Apparently, this is insufficient. I really don't know how I can help you in this case.

**Comment by joengsanyc** [comment]
Okay, thank you very much

**Comment by joengsanyc** [comment]
![Uploading e1e39564dbb242138cb869b53405afa5.png…]()
