### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by joengsanyc** [fuzztruction/fuzztruction#5]
I'm sorry to bother you again. I wonder if this means that I have set up the environment through the build.sh and connected the container through the start.sh.
![Uploading 屏幕截图 2024-03-20 151853.png…]()

**Comment by nbars** [comment]
Hey, I am unable to open the attached picture.

**Comment by joengsanyc** [comment]
![Uploading 屏幕截图 2024-03-20 151853.png…]()

**Comment by joengsanyc** [comment]
![Uploading 屏幕截图 2024-03-20 151853.png…]()

**Comment by joengsanyc** [comment]
![Uploading 屏幕截图 2024-03-20 151853.png…]()

**Comment by joengsanyc** [comment]
![Uploading 屏幕截图 2024-03-20 151853.png…]()

**Comment by joengsanyc** [comment]
Uploading VID_20240320_214332.mp4…

**Comment by joengsanyc** [comment]
I don't know why it won't open. Here is the text message
root@yccc-virtual-machine:/home/yccc/fuzztruction/env# ./start.sh
[+] Creating new container...[+] Using locally build image[+]Using fuzztruction-env:latest as docker image[+] docker run -ti -d --privileged -v /home/yccc/fuzztruction:/home/user/fuzztruction -v /home/yccc/fuzztruction:/home/user/shared -v /home/yccc/fuzztruction/data/zshrc:/home/user/.zshrc -v /home/yccc/fuzztruction/data/zshhistory:/home/user/.zsh history -v /home/yccc/fuzztruction/data/bash history:/home/user/.bash history -v /home/yccc/fuzztruction/data/init.vim:/home/user/.config/nvim/init.vim -v /home/yccc/fuzztruction/data/ccache:/ccache-v /home/yccc/fuzztruction/data/vscode-data:/home/user/.config/code --mount type=tmpfs,destination=/tmp,tmpfs-mode=777 --ulimit msgqueue=2097152000--shm-size=16G --net=host --name fuzztruction-env --enV PREBUILT ENV VARNAME=USE PREBUILT --enV USE PREBUILT= fuzztruction-env:latest[+] Rerun ./start.sh to connect to the new container.


In addition to that, I would like to know how to use this fuzztruction next. Can you give me some help, e.g. a manual?

**Comment by nbars** [comment]
Hey,

To spawn a shell inside the container, you have to execute `./env/start.sh`. Everything else should be documented in the repositories [README.md](https://github.com/fuzztruction/fuzztruction). I'm sorry, but I can not help you any further without specific questions.
