### ISSUE TITLE
A request for Presentation Slides

### ISSUE THREAD

**Issue by DQYXACML** [fuzztruction/fuzztruction#6]
Hello, i recently read your paper titled “Fuzztruction: Using Fault Injection-based Fuzzing to
Leverage Implicit Domain Knowledge” and found it extremely insightful. I would like to share it with others, and I was wondering if you have a PPT related to the paper that you could share. It would greatly enhance the discussion.

**Comment by DQYXACML** [comment]
oh, i find the Presentation Video in YouTube, and it is very helpful to me. Thank you!

**Comment by nbars** [comment]
I am glad that you found the presentation helpful :)
